name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint-github-pr-check
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint_flags: 'testdata/'
